# Generated by Django 5.2.3 on 2025-09-08 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_text_color',
            field=models.CharField(default='#1f2937', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code.')]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_text_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code.')]),
        ),
    ]
