# Generated by Django 5.2.1 on 2025-09-09 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_header_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_color',
            field=models.CharField(default='#1e40af', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code.')]),
        ),
    ]
