# Generated by Django 5.2.1 on 2025-09-09 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_sidebar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_nav_text_color',
            field=models.CharField(default='#1f2937', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code.')]),
        ),
    ]
