# Generated by Django 5.2.1 on 2025-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_driver_name',
            field=models.CharField(blank=True, help_text='Name of currently assigned driver', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_driver_phone',
            field=models.CharField(blank=True, help_text='Phone number of current driver', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current GPS latitude', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current GPS longitude', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='gps_device_id',
            field=models.CharField(blank=True, help_text='GPS device or tracking device ID', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Last time GPS location was updated', null=True),
        ),
    ]
