# Generated by Django 5.2.3 on 2025-10-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_current_driver_name_bus_current_driver_phone_and_more'),
        ('gps_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Currently assigned driver for this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to='gps_tracking.driver'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_driver_name',
            field=models.CharField(blank=True, help_text='Name of currently assigned driver (deprecated - use assigned_driver)', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_driver_phone',
            field=models.CharField(blank=True, help_text='Phone number of current driver (deprecated - use assigned_driver)', max_length=20),
        ),
    ]
