# Generated by Django 5.2.1 on 2025-08-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0002_bus_current_driver_name_bus_current_driver_phone_and_more'),
        ('routes', '0002_route_destination_terminal_route_origin_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('center_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('center_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('radius_meters', models.IntegerField(help_text='Radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('alert_on_entry', models.BooleanField(default=False)),
                ('alert_on_exit', models.BooleanField(default=False)),
                ('speed_limit', models.FloatField(blank=True, help_text='Speed limit in km/h', null=True)),
                ('area_type', models.CharField(choices=[('terminal', 'Bus Terminal'), ('school_zone', 'School Zone'), ('hospital_zone', 'Hospital Zone'), ('residential', 'Residential Area'), ('highway', 'Highway'), ('maintenance', 'Maintenance Zone')], default='terminal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('speed', models.FloatField(default=0.0, help_text='Speed in km/h')),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_at_terminal', models.BooleanField(default=False)),
                ('terminal_name', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, help_text='GPS device or phone ID', max_length=100)),
                ('battery_level', models.IntegerField(blank=True, help_text='Device battery percentage', null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='buses.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_driver', to='buses.bus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('panic', 'Panic Button'), ('breakdown', 'Vehicle Breakdown'), ('accident', 'Accident'), ('medical', 'Medical Emergency'), ('security', 'Security Threat'), ('fire', 'Fire Emergency')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('authorities_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='buses.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='gps_tracking.driver')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_tracking.buslocation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_emergencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_start_time', models.DateTimeField()),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('distance_covered', models.FloatField(default=0.0, help_text='Distance covered in km')),
                ('total_distance', models.FloatField(help_text='Total route distance in km')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('delay_reason', models.TextField(blank=True)),
                ('driver_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_progress', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
            options={
                'ordering': ['-journey_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpeedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overspeed', 'Over Speed Limit'), ('reckless', 'Reckless Driving'), ('sudden_brake', 'Sudden Braking'), ('rapid_acceleration', 'Rapid Acceleration'), ('idle_too_long', 'Idle Too Long')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('recorded_speed', models.FloatField(help_text='Speed at time of alert (km/h)')),
                ('speed_limit', models.FloatField(help_text='Speed limit for the area (km/h)')),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_alerts', to='buses.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_alerts', to='gps_tracking.driver')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_tracking.buslocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['bus', 'timestamp'], name='gps_trackin_bus_id_0f43f6_idx'),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['timestamp'], name='gps_trackin_timesta_5c7549_idx'),
        ),
    ]
